on:
  release:
    types: [published]

name: ImmersiveRailroading Release Build

jobs:
  build:
    name: Build & upload (${{ matrix.branch }})
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        branch: [1.7.10-forge, 1.10.2-forge, 1.11.2-forge, 1.12.2-forge, 1.14.4-forge, 1.15.2-forge, 1.16.5-forge]
      fail-fast: false

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 1.8
      uses: actions/setup-java@v5
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: keyscan
      run: mkdir -p ~/.ssh/ && ssh-keyscan -t rsa teamopenindustry.cc >> ~/.ssh/known_hosts
    - name: Install deps
      run: sudo apt install -y pngquant findutils xvfb
    - name: Setup Universal Mod Core (and helpers)
      env:
        BRANCH: ${{ matrix.branch }}
      run: java -jar UMCSetup.jar ${BRANCH} https
    - name: Modify build.gradle to Include LuaJ and Merge JARs
      run: |
        echo "" >> build.gradle
        echo "repositories {" >> build.gradle
        echo "    flatDir { dirs 'libs' }" >> build.gradle
        echo "}" >> build.gradle
        echo "" >> build.gradle
        echo "dependencies {" >> build.gradle
        echo "    implementation fileTree(dir: 'libs', include: ['*.jar'])" >> build.gradle
        echo "}" >> build.gradle
        echo "" >> build.gradle
        echo "jar {" >> build.gradle
        echo "    duplicatesStrategy = DuplicatesStrategy.EXCLUDE" >> build.gradle
        echo "    from {" >> build.gradle
        echo "        fileTree(dir: 'libs', include: ['*.jar']).collect { zipTree(it) }" >> build.gradle
        echo "    }" >> build.gradle
        echo "}" >> build.gradle
    - name: Gradle compile
      run: ./gradlew classes
    - name: Process images
      run: find src/main/resources/assets/immersiverailroading/ | grep png | xargs -I foo pngquant -s1 -f --ext .png foo
    - name: Gradle build
      run: ./gradlew build -Dtarget=release
    - name: Gradle publish
      env:
        MAVENCI_PASS: ${{ secrets.MAVENCI_PASS }}
      run: ./gradlew publish -Dtarget=release
    - uses: actions/upload-artifact@v6
      with:
        name: Immersive Railroading ${{matrix.branch}}
        path: build/libs/ImmersiveRailroading-${{matrix.branch}}*
